# pip install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: KotlinPoet
repo_name: KotlinPoet
repo_url: https://github.com/square/kotlinpoet
site_description: "A Kotlin API for generating .kt source files"
site_author: Square, Inc.
remote_branch: gh-pages

copyright: 'Copyright &copy; 2015 Square, Inc.'

theme:
  name: 'material'
  logo: 'images/icon-square.png'
  favicon: 'images/icon-square.png'
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'cyan'
      accent: 'deep-purple'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'blue-grey'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

nav:
  - 'Overview':
    - 'Code & Control Flow': code-control-flow.md
    - 'Format Specifiers':
      - '%S for Strings': s-for-strings.md
      - '%P for String Templates': p-for-string-templates.md
      - '%T for Types': t-for-types.md
      - '%M for Members': m-for-members.md
      - '%N for Names': n-for-names.md
      - '%L for Literals': l-for-literals.md
      - 'Code Block Format Strings': code-block-format-strings.md
    - 'Functions': functions.md
    - 'Constructors': constructors.md
    - 'Parameters': parameters.md
    - 'Properties': properties.md
    - 'Interfaces': interfaces.md
    - 'Objects': objects.md
    - 'Enums': enums.md
    - 'Anonymous Inner Classes': anonymous-inner-classes.md
    - 'Annotations': annotations.md
    - 'Type Aliases': type-aliases.md
    - 'Callable References': callable-references.md
    - 'kotlin-reflect': kotlin-reflect.md
  - 'Interop - JavaPoet': interop-javapoet.md
  - 'Interop - kotlin-metadata': interop-kotlin-metadata.md
  - 'Interop - KSP': interop-ksp.md
  - 'API':
    - 'kotlinpoet': 1.x/kotlinpoet/index.html
    - 'interop-javapoet': 1.x/interop-javapoet/index.html
    - 'interop-kotlinx-metadata': 1.x/interop-kotlinx-metadata/index.html
    - 'interop-ksp': 1.x/interop-ksp/index.html
  - 'Stack Overflow ‚èè': https://stackoverflow.com/questions/tagged/kotlinpoet?sort=active
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
